services:
  nginx:
    container_name: g_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      args:
        PHP_FPM_SERVER: g_php
        PHP_FPM_PORT: 9000
    ports:
      - '${DOCKER_NGINX_PORT-8000}:80'
    volumes:
      - './public:/var/www/html/public'
    networks:
      - backend
    depends_on:
      - php

  php:
    container_name: g_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        XDEBUG: 'true'
    volumes:
      - '.:/var/www/html'
      - './docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
    networks:
      - backend

networks:
  backend:
    name: g_network
    driver: bridge

volumes:
  mysql-data:
    driver: local
